# Generated by Django 3.0.5 on 2020-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=(0, 'MALE'), help_text='Gender',
                                   max_length=8),
        ),
    ]
